site_name: Robot Vision
site_description: General template for a robot vision application using the wenglor robot vision interface.
site_url: https://wenglor.github.io/wenglor-robot-vision/
repo_url: https://github.com/wenglor/wenglor-robot-vision
repo_name: wenglor-robot-vision
use_directory_urls: true

theme:
  name: material
  logo: images/wenglor_logo.svg
  features:
    - navigation.indexes
    - content.code.copy
    - toc.integrate
    - search.highlight

nav:
  - index.md
  - 1_0_0_intended_purpose.md
  - 2_0_0_network_overview.md
  - 3_0_0_robot_vision_basics.md
  - 4. Wenglor Robot Server:
      - 4_0_robot_vision_server/index.md
      - 4.1 Basics with Robot Server:
          - 4_0_robot_vision_server/4_1_basics/index.md
          - 4_0_robot_vision_server/4_1_basics/4_1_1_camera_on_robot.md
          - 4_0_robot_vision_server/4_1_basics/4_1_2_camera_not_on_robot.md
      - 4_0_robot_vision_server/4_2_0_settings_on_device_website.md
      - 4_0_robot_vision_server/4_3_0_calibration_job_in_univision.md
      - 4_0_robot_vision_server/4_4_0_detection_job_in_univision.md
      - 4_0_robot_vision_server/4_5_0_generic_robots.md
      - 4_0_robot_vision_server/4_6_0_generic_robot_vision_api.md
  - 5_0_0_change_index_of_operating_instructions.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.snippets

docs_dir: docs

extra:
  generator: false

copyright: "© 2025 wenglor sensoric group"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/wenglor.css
  - css/images_table.css